hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dataset: cnn_dm
  - trainer: default

mode:
  dataset: cnn_dm
  model: bertsum

train_checkpoint:
test_checkpoint:

model:
  base_checkpoint: bert-base-uncased
  enc_num_layers: 2
  enc_intermediate_size: 2048
  enc_num_attention_heads: 8
  enc_dropout_prob: 0.1

max_seq_len: 512
batch_size: 16

engine:
  sum_size: 3
  n_block: 3
  freeze_base: False
  lr: 2e-3
  betas: [0.9, 0.999]
  num_warmup_steps: 10000
  save_result: True

log:
  project: OrderSum--${mode.dataset}
  name: ${mode.model}--exp_0--${now:%Y-%m-%d}/${now:%H-%M-%S}
  save_dir: ./log
